#!/bin/bash
#
if [ ! -z "$2" ] ; 
then 
    FOUND_LIST=`find . \( -name "$1" -o -name "$2" \)` 
else
    FOUND_LIST=`find . -name "$1"` 
fi
#
#
if [ $? -eq 0 ] ; then 
    if [ "${FOUND_LIST}" != "" ] ; then 
        echo "${FOUND_LIST}" | xargs realpath
    fi 
fi
