#!/bin/bash
#
# bba 
#

if [ "$1" = "" ] ; then 
    printf '\nERROR-1: bitbake recipe name not found!\n'
    exit 1
fi 
BB_NAME="$1"

shift 1

if [ "$1" = "" ] ; then 
    printf '\nERROR-2: bitbake do_action not found!\n'
    exit 2
fi 

LOOP=0
while [ ! "$1" = "" ] ; 
do 
    LOOP=$((LOOP+1))
    BB_ACTION="$1"
    asc yellow
    printf '\n### LOOP=%d, INFO: bitbake -f -c %s %s ###\n\n' ${LOOP} "${BB_ACTION}" "${BB_NAME}"
    asc reset
    bitbake -f -c ${BB_ACTION} ${BB_NAME} 2>&1 | tee ${BB_NAME}-${BB_ACTION}.log
    if [ $? -ne 0 ] ; then 
        printf '\nERROR-9: bitbake -f -c %s %s failed!\n' "${BB_ACTION}" "${BB_NAME}"
        exit 9 
    fi 
    shift 1
done
