#!/bin/bash
#
# bbcc 
#
if [ "$1" = "" ] ; then 
    printf 'ERROR-1: first input, bitbake do_action not found!\n'
    exit 1
fi 

LOOP=0
while [ ! "$1" = "" ] ; 
do 
    LOOP=$((LOOP+1))
    asc yellow
    printf '\n### LOOP=%d, INFO: bbcc %s ###\n\n' ${LOOP} "${1}"
    asc reset
    bba $1 clean compile
    shift 1
done

if [ ! "$2" = "" ] ; then 
    bblog $1 "$2"
fi 
