#!/bin/bash
#
# bblog 
#

PRINT_ABS_PATH=0 
WORK_PATH_ARM="build_output/work/aarch64-soniccorex-linux"
WORK_PATH="build_output/work/corei7-64-soniccorex-linux"
FIND_DIR="temp"

if [[ ! -d "${WORK_PATH}" ]] ; then 
    printf '\nERROR-01: %s: base work path %s not found!\n' "$0" "${WORK_PATH}"
    exit 1
else 
    cd ${WORK_PATH}
    if [[ $? -ne 0 ]] ; then 
	printf '\nERROR-02: %s: cd %s failed\n' "$0" "${WORK_PATH}"
	exit 2
    fi 
fi 

if [[ -z "$1" ]] ; then 
    asc red
    printf '\nERROR-03: %s: No PROJECT recipe specified!\n' "$0"
    printf '\nINFO: latest projects from PATH= ' 
    asc magenta
    printf '\"%s\"\n' "$(pwd)"
    asc green
    ls -ltr | tail 
    asc reset
    exit 3   
fi 

if [[ ! -d "$1" ]] ; then 
    asc red
    printf '\nERROR-04: %s: RECIPE_PATH= ' "$0" 
    asc magenta
    printf '%s' "$1" 
    asc green
    printf ' not found!\n'
    printf ' PWD= ' 
    asc magenta
    printf '%s\n' "$(pwd)" 
    asc reset
    exit 4
else 
    cd $1
fi 

# change find -ftype to d,  "temp" directory 
#LOG_PATH=`fx -t=d ${FIND_DIR}` 
LOG_PATH="`find . -type d -name ${FIND_DIR}`" 
N_DIR_FOUND="`echo ${LOG_PATH} | wc -l`"
if [[ ${N_DIR_FOUND} -ne 1 ]] ; then 
    printf '\nERROR-05: number of Dir \"%s\" found is not 1\n' "${LOG_DIR_NAME}"
    exit 5
fi 
if [[ -z "${LOG_PATH}" ]] ; then 
    printf 'ERROR-06: %s: find DIR=\"%s\" at PATH=\"%s\" not found!\n' "$0" "${FIND_DIR}" "$(pwd)"
    exit 6 
else 
    asc green
    printf '\n build project %s path='
    asc magenta
    printf '%s' "$(pwd)" 
    asc green
    printf '\n LOG_PATH='
    asc magenta
    printf '%s' "${LOG_PATH}" 
    asc reset
    if [[ -z "$2" ]] ; then 
        asc red 
        printf '\n\nERROR-07: %s:' "$0"
        asc YELLOW
        printf ' No search pattern specified!\n' 
        asc reset
        exit 7
    fi
    printf ', grep pattern='
    asc magenta
    printf '\"%s\"\n' "$2"
    printf '\n' 
    asc reset 
    if [[ ${PRINT_ABS_PATH} -ne 0 ]] ; then  
        START_LOG_PATH="`realpath ${LOG_PATH}`"
    else
        START_LOG_PATH="${LOG_PATH}"
    fi 
    asc green 
    printf 'INFO: call fx with: '
    asc yellow
    printf '\tfx -fp=%s -all \"%s\"\n' "${START_LOG_PATH}" "$2"
#
    asc reset
    if [[ ! -d "${START_LOG_PATH}" ]] ; then 
	printf '\nERROR:-09: %s: START_LOG_PATH=\"%s\" Does not Exist!' "$0" "${START_LOG_PATH}"
	exit 9 
    fi 
    fx -fp=${START_LOG_PATH} -all "$2"

#
fi
