#!/bin/bash
#
# bblog 
#

WORK_PATH="build_output/work/aarch64-soniccorex-linux"

if [ ! -d "${WORK_PATH}" ] ; then 
    printf 'ERROR-1: base work path %s not found!\n' "${WORK_PATH}"
    exit 1
else 
    cd ${WORK_PATH}
fi 

if [ "$1" = "" ] ; then 
    printf 'ERROR-2: no input for recipe work path!\n' 
    printf '=== TAIL of start of work path: \"%s\"\n' "${WORK_PATH}"
    ls -ltr | tail 
    exit 2   
fi 

if [ ! -d "$1" ] ; then 
    printf 'ERROR-3: work path %s not found! PWD=%s\n' "${1}" "$(pwd)"
    exit 3
else 
    cd $1
fi 

LOG_PATH=`fx -t=d temp` 
if [ "${LOG_PATH}" = "" ] ; then 
	printf 'ERROR-4: log file path not found!\n'
        exit 4 
else 
	if [ "$2" = "" ] ; then 
		printf 'ERROR-5: not input search string!\n' 
                exit 5
	else 
		fx -fp=${LOG_PATH} -all "$2"
	fi
fi
