#!/bin/bash

#if [[ -z "${CFLAGS}" ]]; then
#    CFLAGS="-Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wconversion -g -lm -lpthread" 
#fi

CFLAGS="${CFLAGS} -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wconversion -g -lm -lpthread"

if [[ -z "${CC}" ]]; then
    CC="clang"
fi
if [[ -z "${CPP}" ]]; then
    CPP="clang++"
fi

if [[ -z "$1" ]]; then
    printf '\nUsage: cc1 filename_without.c'
    echo
    printf '\n\t Example: cc1 hello.c\n\n' 
    exit 1
fi

LOOP=0
while [[ ! -z "$1" ]]; 
do  
    LOOP=$((LOOP+1))
    INPUT="$1"
    if [[ -f "${INPUT}" ]]; then 
        PRIMARY_NAME="${INPUT%%.*}"
        EXTENSION_NAME="${INPUT##*.}"
        OBJ_FILE="${PRIMARY_NAME}"
        SRC_FILE="${INPUT}"
        if [[ "${EXTENSION_NAME}" == "c" ]]; then
            COMPILER="${CC}"
        elif [[ "${EXTENSION_NAME}" == "cpp" ]]; then
            COMPILER="${CPP}"
        else
            printf 'Source File \"%s\" Type unknown, Extension found: %s\n' "${INPUT}" "${EXTENSION_NAME}"
        fi
    else
        printf 'Source File: \"%s\" not found!\n' "${INPUT}"
        exit 2 
    fi
    if [[ -e "${OBJ_FILE}" ]]; then 
        printf 'INFO: remove old executable \"%s\"\n' "${OBJ_FILE}"
        rm ${OBJ_FILE} 
    fi 

    echo =====================================================================================
    printf '%s %s %s -o %s\n' "${COMPILER}" "${CFLAGS}" "${SRC_FILE}" "${OBJ_FILE}"
    echo =====================================================================================
    ${COMPILER} ${CFLAGS} ${SRC_FILE} -o ${OBJ_FILE}

    if [[ -f "${OBJ_FILE}" ]]; then 
        echo =====================================================================================
        ls -l ${OBJ_FILE}
    else
        printf '\nERROR: build failed, cannot find obj: %s\n' "${OBJ_FILE}"
        exit 9
    fi
    shift 1
done
