#!/bin/bash
# 
# cht
#

LOOP=0
while [ ! "$1" = "" ] ; 
do 
	LOOP=$((LOOP+1))
	asc magenta
	echo === ${LOOP} ========================================================
	asc reset
	curl cht.sh/$1
	shift 1
done
