#!/bin/bash
#

S_FULLNAME=`realpath $0`
S_BASENAME=`basename $0`

if [ "$1" = "--help" -o "$1" = "-h" ] ; then 
    printf '\n search *.bb and *.bbappend multiple text pattern, always start from current path\n'
    printf '\n Usage: %s  pattern1 [pattern2]...\n\n' "${S_BASENAME}"
    exit 1
fi

if [ -z "$1" ] ; then 
    find . -type f \( -name '*.bb' -o -name '*.bbappend' -o -name '*.inc' -o -name '*.bbclass' -o -name '*.conf' \) ${FIND_OPT} 
else 
    while [ ! -z "$1" ] ;
    do
    # '*.bb *.bbappend *.inc *.bbclass *.conf'

    #    echo 
    #    echo " Searching: \"$1\"", Path: `pwd`  
    #    echo 
    #    find . \( -name "make*" -o -name "Make*" -o -name "*.mk" -o -name "*.mak" \) -exec fgrep -H "$1" {} \;
    #    find . -type f \( -name "make*" -o -name "Make*" -o -name "*.mk" -o -name "*.mak" \) | xargs fgrep -H "$1" 
    #    find . -type f \( -name '*.bb' -o -name '*.bbappend' -o -name '*.inc' -o -name '*.bbclass' -o -name '*.conf' \) ${FIND_OPT} -print0 | xargs -0 fgrep ${GREP_OPT} "$1"
        find . -type f \( -name '*.bb' -o -name '*.bbappend' -o -name '*.inc' -o -name '*.bbclass' -o -name '*.conf' \) ${FIND_OPT} -print0 | xargs --null fgrep ${GREP_OPT} "$1"
        shift 1
    done
fi
