#!/bin/bash
#
if [ -z "$1" ] ; then 
    echo
    echo ' search Makefile and *.mk and *.mak files for multiple text pattern, always start from current path'
    echo 
    echo "Usage: fmk  pattern1 [pattern2]..."
    echo         
    exit 1
fi
while [ ! -z "$1" ] ;
do
    echo 
    echo " Searching: \"$1\"", Path: `pwd`  
    echo 
#    find . \( -name "make*" -o -name "Make*" -o -name "*.mk" -o -name "*.mak" \) -exec fgrep -H "$1" {} \;
#    find . -type f \( -name "make*" -o -name "Make*" -o -name "*.mk" -o -name "*.mak" \) | xargs fgrep -H "$1" 
    find . -type f \( -name 'make*' -o -name 'Make*' -o -name '*.mk' -o -name '*.mak' -o -name "GNUmake*" \) | xargs fgrep -H "$1" 
    shift 1
done
