#!/bin/bash
if [ ! -z "$2" ] ; 
then 
	find . -type f -maxdepth 1 \( -name "$1" -o -name "$2" \) 
#	find . \( -name "$1" -o -name "$2" \) 
else
	find . -type f -maxdepth 1 -name "$1" 
#	find . -name "$1" 
fi
