#!/bin/bash
#

FIND_OPT="-maxdepth 1 -type f"

while [[ "$1" != "" ]]
do
    FILES="`find . ${FIND_OPT} -name "${1}"`"
    if [[ "${FILES}" != "" ]] ; then
	find . ${FIND_OPT} -name "${1}" | xargs sed -i 's/[ \t]*$//'
    fi
    shift 1
done
