#!/bin/bash
#

s_VERSION="1.7"
EXE_NAME="`realpath $0`"
EXE_BASE="`basename ${EXE_NAME}`"
EXE_DIR="`dirname ${EXE_NAME}`"
START_LINE_MIN="1"
CMD_BLK_BORDER="============================"
b_VERBOSE=0
b_DEBUG=0

COLOR="${EXE_DIR}/asc"

START_LINE="${START_LINE_MIN}"
if [[ "$1" != "" ]]; then 
    if [[ ! -f "$1" ]]; then  
        if [[ "$1" =~ ^[0-9]+$ ]]; then 
            START_LINE="$1"
        fi 
        shift 1
    fi
fi

if [[ ${START_LINE} -lt ${START_LINE_MIN} ]]; then 
    printf '\nERROR-00: %s from number %d is inavlid!, first valid number is %d\n' "${EXE_NAME}" ${START_LINE} ${START_LINE_MIN}
    exit 1 
fi 

N_ERROR=0
N_LINES=0
while read line
do
    let N_LINES+=1
    if [[ ${N_LINES} -ge ${START_LINE} ]]; then
        ${COLOR} CYAN
        printf '\n%s ' "${CMD_BLK_BORDER}"
        printf ' %4d: Run ' ${N_LINES} 
        ${COLOR} YELLOW
        printf '\"%s\" ' "${line}"
        ${COLOR} CYAN
        printf ' %s\n' "${CMD_BLK_BORDER}"
        ${COLOR} reset
        if [[ ${line} == "" ]]; then 
		break;
        fi 
        if [[ -x "${line}" ]]; then 
                pushd . >/dev/null
        	DIR_NAME="`dirname ${line}`"
                FULL_DIR_NAME="`realpath ${DIR_NAME}`"
        	CMD_NAME="`basename ${line}`"
        	if [[ "${DIR_NAME}" != "" ]]; then 
        	    cd ${DIR_NAME}
        	    if [[ $? -ne 0 ]]; then 
        	        printf '\nERROR-01: N_LINES=%d: \"cd %s\" failed!\n' ${N_LINES} "${DIR_NAME}"
        		let N_ERROR+=1
        	    fi 
        	fi 
        	if [[ "${CMD_NAME}" != "" ]]; then 
#        	    bash -c ./${CMD_NAME}
	       	    time ./${CMD_NAME}
           	    if [[ $? -ne 0 ]]; then 
                        ${COLOR} RED
        	        printf '\nERROR-02: CMD Dir Path: '
                        ${COLOR} YELLOW
                        printf '\"%s\"\n' "${FULL_DIR_NAME}"
                        ${COLOR} CYAN
                        printf ' %4d: Run ' ${N_LINES}
                        ${COLOR} YELLOW
                        printf '\"./%s\"' "${CMD_NAME}"
                        ${COLOR} RED
                        printf ' failed!\n'
                        ${COLOR} reset
        		let N_ERROR+=1
        	    fi 
        	else
        	    printf '\nERROR-03: N_LINES=%d: Got empty basename \"%s\" from input \"%s\"\n' ${N_LINES} "${CMD_NAME}" "${line}"
        	    let N_ERROR+=1
        	fi 
                popd >/dev/null
        else 
        	${line}
        	if [[ $? -ne 0 ]]; then 
        	    printf '\nERROR-04: N_LINES=%d: \"cd %s\" failed!\n' ${N_LINES} "${line}"
        	    let N_ERROR+=1
        	fi 
        fi 
    else
	${COLOR} CYAN
	printf ' %4d: Skiping: ' ${N_LINES}
     	${COLOR} RED
	printf '\"%s\"\n' "${line}"
	${COLOR} reset
    fi
    if [[ ${N_ERROR} -ne 0 ]]; then 
        break
    fi 
done < "${1:-/dev/stdin}"
#
${COLOR} GREEN
if [[ ${START_LINE} -gt 1 ]]; then 
    printf '\n Input Lines Skipped: '
    ${COLOR} YELLOW
    let START_LINE-=1
    printf '%d to %d\n' ${START_LINE_MIN} ${START_LINE}
fi
${COLOR} GREEN
printf ' Total Input lines: '
${COLOR} YELLOW
printf '%d\n' ${N_LINES}

if [[ ${N_ERROR} -ne 0 ]]; then 
    ${COLOR} RED
    printf 'ERROR-99: Number of Errors: %d\n' ${N_ERROR}
fi 
${COLOR} reset
exit ${N_ERROR}

